export * from './Header'
export * from './HeroSection'
export * from './AboutSection'
export * from './LicensesSection'
export * from './MainGoalSection'
export * from './ServicesDetailedSection'
export * from './Footer'
export * from './HeaderMobile'
